### ISSUE TITLE
Errors Installing on Mac

### ISSUE THREAD

**Issue by jamesg311** [Sunoo/homebridge-philips-air#10]
Hi there, I'm having trouble installing the plugin (previously had no trouble before this new version to support updated Philips models).

I receive the below error and have been banging my head against the keyboard trying to fix it.

USER: James
DIR: /usr/local/lib
CMD: sudo -E -n npm install homebridge-philips-air@latest

> node-calls-python@1.4.0 install /usr/local/lib/node_modules/homebridge-philips-air/node_modules/node-calls-python
> node-gyp rebuild

  CXX(target) Release/obj.target/nodecallspython/src/addon.o
  CXX(target) Release/obj.target/nodecallspython/src/pyinterpreter.o
  SOLINK_MODULE(target) Release/nodecallspython.node
ld: library not found for -lpython3.7m
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/nodecallspython.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-philips-air/node_modules/node-calls-python
gyp ERR! node -v v12.18.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-calls-python@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-calls-python@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/James/.npm/_logs/2020-06-17T08_31_27_961Z-debug.log

Command failed. Please review log for details.

**Comment by jamesg311** [comment]
Troubleshooting steps I've tried:

- Reinstalling Python3
- Reinstalling pip
- Reinstalling node
- Downgrading node to an earlier version
- Removing Python 2.7

I've tried searching these error messages on StackOverflow and typing in all kinds of different terminal commands and re-running the installation and it continues to fail with the same message.

**Comment by Sunoo** [comment]
If the old version worked for you, you could remove this version and install homebridge-philips-air-httponly. No need to adjust your config, just make sure you don’t have both installed.

However, I’d like to get to the bottom of this error. Can you let me know what operating system you’re running?

**Comment by jamesg311** [comment]
Old version never worked since I have one of the units your latest update is supposed to add support for. M
Running macOS 10.5.5

**Comment by Sunoo** [comment]
Ah, I’ve not tested it on the Mac, but fortunately I do own one. I’ll see if I can test on that soon and figure this out.

**Comment by MattCheetham** [comment]
Experiencing the same issue on my raspberry pi. Set the package updating and get an error thrown. Tried installing it fresh and still getting the error.

On my phone so can’t copy the log right now but the main line of the error is “python3-config not found. gyp: Call to ‘python3-config —libs’ returned exit status 127 while in binding .gyp. While trying to load binding .gyp

I’ll copy the full logs next time I’m at a computer.

**Comment by Sunoo** [comment]
@MattCheetham That seems to be a slightly different issue (unless I missed that error in the first post?). Are you sure you ran the apt install commands? It sounds like you might not have Python installed.

**Comment by MattCheetham** [comment]
Ah perhaps it’s a separate issue. I use the raspberry pi HomeBridge image with the built in HomeBridge Config UI X to install packages. Normally just works fine as it’s all done via a GUI. I’ve switched to the HTTP only version and it works so I’ll just stick with that.

**Comment by Sunoo** [comment]
I wish I could pop up a warning in Config UI X during install, but I’m not aware of any way to do that unfortunately.

**Comment by dsadsa897897r** [comment]
I also get this error on upgrade - running as HomeBridge image

bin/sh: python3-config: not found
gyp: Call to 'python3-config --libs' returned exit status 127 while in binding.gyp.

**Comment by Sunoo** [comment]
@dsadsa897897r You don’t have Python installed. Either follow the steps in the installation instructions or uninstall the plugin and switch to the httponly version if you have a model that uses the HTTP protocol (given you are upgrading this seems likely).

**Comment by Sunoo** [comment]
Okay, I've just pushed a new version of this that removes node-calls-python, so that should resolve the problems you were seeing. If you have any other issues, please feel free to open another issue and I'll do my best to assist.

**Comment by jamesg311** [comment]
Confirming installation was successful! On to setup! Thank you 🙏🏻

**Comment by Sunoo** [comment]
Fantastic, that’s great to hear!
