### ISSUE TITLE
List of Supported Philips Air Purifiers ?

### ISSUE THREAD

**Issue by andrewbulloch** [Sunoo/homebridge-philips-air#117]
Hi David, would be interested to know if your plug-in supports the Philips Series 1000ai ?  Apologies if you have a list of supported devices somewhere here, I couldn't find it in the code on GitHub or in the Hoobs directory.

Thanks

**Comment by Sunoo** [comment]
I don’t believe I’ve heard reports one way or the other of that being tested.
