### ISSUE TITLE
Config issues (HOOBS)

### ISSUE THREAD

**Issue by ethempekin** [Sunoo/homebridge-philips-air#13]
Switched to this one but still running issues.

21/06/2020, 22:20:57 [Bedroom Air Prufier] Initializing platform accessory undefined...
21/06/2020, 22:20:57 TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, Buffer, TypedArray, or DataView. Received type undefined
    at Hash.update (internal/crypto/hash.js:70:11)
    at Object.generate (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/hap-nodejs/dist/lib/util/uuid.js:10:13)
    at philipsAir.addAccessory (/home/hoobs/.hoobs/node_modules/homebridge-philips-air-httponly/index.js:332:28)
    at /home/hoobs/.hoobs/node_modules/homebridge-philips-air-httponly/index.js:40:14
    at Array.forEach (<anonymous>)
    at philipsAir.didFinishLaunching (/home/hoobs/.hoobs/node_modules/homebridge-philips-air-httponly/index.js:39:25)
    at API.emit (events.js:228:7)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:104:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)

**Comment by Sunoo** [comment]
Can you share your config.json? It looks like perhaps IP isn’t set correctly?

**Comment by ethempekin** [comment]
Sure.

      {
            "platform": "philipsAir",
            "plugin_map": {
                "plugin_name": "homebridge-philips-air-httponly"
            },
            "name": "Bedroom Air Prufier",
            "devices": [
                "192.168.1.49"
            ]
        }

**Comment by Sunoo** [comment]
Looks like you’ve got things all mixed up, given the values you provided it should look like this:

      {
            "platform": "philipsAir",
            "devices": [{
                "name": "Bedroom Air Prufier",
                “ip”: "192.168.1.49"
            }]
        }

Did you create that config by hand, or was is automatically created by HOOBS somehow? I’ve never used HOOBS, so I’m not very familiar with it.

**Comment by ethempekin** [comment]
Ah, was hoobs created.

**Comment by Sunoo** [comment]
Interesting, sounds like HOOBS is messing things up somehow, I guess I should install it somewhere and take a look...

If you change your config to be the one I posted, does it work for you?

**Comment by ethempekin** [comment]
With this change back to functioning hoobs, maybe i should switch to homebridge.... 

Thank you

**Comment by Sunoo** [comment]
I’d personally recommend Homebridge, they even offer a pre-set-up OS image now like HOOBS does.

I will try to see if I can support HOOBS, but their monetizing of other people’s open source work has always kinda rubbed me the wrong way.

**Comment by ethempekin** [comment]
Yes i think this will be wise for me to make the effort.

**Comment by Sunoo** [comment]
I looked into HOOBS' configuration schema, and I can't make it any cleaner than it is already. Looks like other plugins have the same ugliness there as well.
