### ISSUE TITLE
Problem installing node-calls-python

### ISSUE THREAD

**Issue by apache1973** [Sunoo/homebridge-philips-air#14]
Hello
I have a problem installing the plugin. Below log

> node-calls-python@1.4.0 install /opt/nodejs/lib/node_modules/homebridge-philips-air/node_modules/node-calls-python
> node-gyp rebuild

make: Entering directory '/opt/nodejs/lib/node_modules/homebridge-philips-air/node_modules/node-calls-python/build'
  CXX(target) Release/obj.target/nodecallspython/src/addon.o
../src/addon.cpp: In function ‘napi_value__* nodecallspython::createHandler(napi_env, nodecallspython::PyInterpreter*, const string&)’:
../src/addon.cpp:87:19: error: ‘napi_add_finalizer’ was not declared in this scope
         CHECKNULL(napi_add_finalizer(env, result, new Handler(py, stringhandler), Handler::Destructor, nullptr, nullptr));
                   ^~~~~~~~~~~~~~~~~~
../src/addon.cpp:13:31: note: in definition of macro ‘CHECKNULL’
 #define CHECKNULL(func) { if (func != napi_ok) { napi_throw_error(env, "error", #func); return nullptr; } }
                               ^~~~
../src/addon.cpp:87:19: note: suggested alternative: ‘napi_finalize’
         CHECKNULL(napi_add_finalizer(env, result, new Handler(py, stringhandler), Handler::Destructor, nullptr, nullptr));
                   ^~~~~~~~~~~~~~~~~~
../src/addon.cpp:13:31: note: in definition of macro ‘CHECKNULL’
 #define CHECKNULL(func) { if (func != napi_ok) { napi_throw_error(env, "error", #func); return nullptr; } }
                               ^~~~
make: *** [nodecallspython.target.mk:100: Release/obj.target/nodecallspython/src/addon.o] Error 1
make: Leaving directory '/opt/nodejs/lib/node_modules/homebridge-philips-air/node_modules/node-calls-python/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.19.66-v7+
gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/nodejs/lib/node_modules/homebridge-philips-air/node_modules/node-calls-python
gyp ERR! node -v v11.5.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-calls-python@1.4.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-calls-python@1.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Please help

**Comment by Sunoo** [comment]
The node-calls-python component seems to be causing a lot of problems for a lot of people. I’m currently in the process of removing that dependancy. Hopefully in next couple of days.

**Comment by summit2g** [comment]
I also have issues with node-calls-python, might be a seperate issue. However if your gonna remove the dependancy then that would fix it too. 

`[7/2/2020, 12:49:24 PM] ====================
[7/2/2020, 12:49:24 PM] ERROR LOADING PLUGIN homebridge-philips-air:
[7/2/2020, 12:49:24 PM] Error: /usr/local/lib/node_modules/homebridge-philips-air/node_modules/node-calls-python/build/Release/nodecallspython.node: undefined symbol: PyBool_Type
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1188:18)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-philips-air/node_modules/node-calls-python/index.js:1:25)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
[7/2/2020, 12:49:24 PM] ====================`

**Comment by Sunoo** [comment]
@summit2g That’s a different error than I’ve seen before from this, but yea, it should be resolved when I remove that. Hoping to have something out during this coming long weekend.

**Comment by Sunoo** [comment]
Okay, I've just pushed a new version of this that removes node-calls-python, so that should resolve the problems you were seeing. If you have any other issues, please feel free to open another issue and I'll do my best to assist.
