### ISSUE TITLE
Errors when loading info on startup (CoAP)

### ISSUE THREAD

**Issue by lumaxis** [Sunoo/homebridge-philips-air#15]
I updated to the new version 2.1.0 today but something is still not properly working. I see this log output:

```
0|homebridge  | [7/3/2020, 6:50:19 PM] [philipsAir] Initializing platform accessory Air Purifier...
0|homebridge  | [7/3/2020, 6:50:20 PM] [philipsAir] Unable to load firmware info: TypeError: Cannot read property 'name' of null
0|homebridge  | [7/3/2020, 6:50:22 PM] [philipsAir] Unable to load status info: TypeError: Cannot read property 'mode' of null
0|homebridge  | [7/3/2020, 6:50:23 PM] [philipsAir] Unable to load filter info: TypeError: Cannot read property 'fltsts0' of null
```

My config still looks like this:

```json
    {
      "platform": "philipsAir",
      "devices": [
        {
          "name": "Air Purifier",
          "ip": "192.168.0.189",
          "protocol": "coap",
          "sleep_speed": true
        }
      ]
    }
```

I double checked that the IP and protocol are correct. `airctrl --ipaddr 192.168.0.189 --protocol coap` yields the following result:

```
[name]                        Name: Air Purifier
[type]                        Type: AC2889
[modelid]                     ModelId: AC2889/10
[swversion]                   Version: 1.0.7
[om]                          Fan speed: 1
[pwr]                         Power: ON
[cl]                          Child lock: False
[aqil]                        Light brightness: 100
[uil]                         Buttons light: 2
[mode]                        Mode: allergen
[pm25]                        PM25: 5
[iaql]                        Allergen index: 2
[aqit]                        Air quality notification threshold: 4
[ddp]                         Used index: IAI
[fltt1]                       HEPA filter type: NanoProtect Filter Series 3 (FY2422)
[fltt2]                       Active carbon filter type: NanoProtect Filter AC (FY2420)
[fltsts0]                     Pre-filter and Wick: clean in 124 hours
[fltsts1]                     HEPA filter: replace in 2232 hours
[fltsts2]                     Active carbon filter: replace in 2164 hours
[ota]                         Over the air updates: ck
[Runtime]                     Runtime: 14.44 hours
[WifiVersion]                 WifiVersion: AWS_Philips_AIR@54.2
[ProductId]                   ProductId: be10acb2e62411e8a1e3061302926720
[DeviceId]                    DeviceId: f0efee38679a11ea99ffba65380a1293
[StatusType]                  StatusType: localcontrol
[ConnectType]                 ConnectType: Localcontrol
```

**Comment by Sunoo** [comment]
Darn, I think I know exactly what the problem is. I should have a fix out this afternoon.

**Comment by Sunoo** [comment]
Can you also do me a favor and run `python3 -V` when you have a chance and let me know what you get? And I’m assuming this was working for you on the previous version, right?

**Comment by lumaxis** [comment]
No, on the previous version I had the seg fault issue from #8, if you remember 🙂 We ascribed that to me running FreeBSD and that not playing well with the node-python library.

The output of `python -V` is `Python 3.7.7`.

**Comment by Sunoo** [comment]
Ah right, I thought you were in one of the old issues, but I couldn’t find it, thanks for the reminder.

I’ll get what I think the fix is in soon, and some more error handling and logging as well, in case I’m wrong about the fix.

**Comment by lumaxis** [comment]
Sounds great! Happy to add some ad-hoc log statements locally or run a debug build too, if that would be of any help. Lmk 👍🏼

**Comment by Sunoo** [comment]
I just spun up a FreeBSD VM and was able to get it working. It looks like by default, there is no python3 in the path. If you `ln -s /usr/local/bin/python3.7 /usr/local/bin/python3` that should make the plugin happy. Could you give that a shot and see if that fixes your problem? If so, I’ll add a config option to specify where to find Python.

**Comment by lumaxis** [comment]
@Sunoo I think there's something wrong with this `if`:
https://github.com/Sunoo/philips-air/blob/3d6c77777d031aa5b31e7c8c9ce2c664a6994bad/pyaircontrol.js#L22-L29

My `output` is 
```json
{"name": "Air Purifier", "type": "AC2889", "modelid": "AC2889/10", "swversion": "1.0.7", "om": "1", "pwr": "1", "cl": false, "aqil": 100, "uil": "2", "dt": 0, "dtrs": 0, "mode": "A", "pm25": 5, "iaql": 2, "aqit": 4, "ddp": "0", "err": 0, "fltt1": "A3", "fltt2": "C7", "fltsts0": 119, "fltsts1": 2227, "fltsts2": 2159, "ota": "ck", "Runtime": 153563857, "WifiVersion": "AWS_Philips_AIR@54.2", "ProductId": "be10acb2e62411e8a1e3061302926720", "DeviceId": "f0efee38679a11ea99ffba65380a1293", "StatusType": "localcontrol", "ConnectType": "Localcontrol"}
```
and hence `start = 0` and `end = 548` which means I end up in the `else` branch and the code returns `null`.

**Comment by lumaxis** [comment]
Was that supposed to be `if (start >= 0 && end > 0) {` or `if (start === 0 && end > 0) {` maybe?

**Comment by Sunoo** [comment]
Well, darn, that’ll do it. I was apparently on completely the wrong track. The HTTP protocol always returns some noise before the first bracket, so I didn’t catch that during my testing. I’ll get that fixed and a new version pushed shortly.

Thanks for your help.

**Comment by Sunoo** [comment]
Fixed philips-air and pushed a new version of this plugin to require the newer version. Fingers crossed that everything is working for you now.

Can't believe it was a single character that messed things up.

**Comment by lumaxis** [comment]
Looking good!

**Comment by Sunoo** [comment]
Fantastic, glad things are working for you now!

**Comment by lumaxis** [comment]
At last 🙂 Thanks for the quick fix!
