### ISSUE TITLE
airctrl not working without sudo

### ISSUE THREAD

**Issue by lhttony** [Sunoo/homebridge-philips-air#16]
Thanks for you great work, I have successfully installed the plugin and I can confirmed that my purifier is using plain_coap
by below testing :

sudo airctrl --ipaddr 192.168.1.40 --protocol plain_coap
[name]        Name: AirPurifier
[modelid]     ModelId: AC4558/31
[swversion]   Version: 1.0.1
[StatusType]  StatusType: localcontrol
[ota]         Over the air updates: no
[Runtime]     Runtime: 12.46 hours
[pwr]         Power: ON
[pm25]        PM25: 4
[iaql]        Allergen index: 1
[mode]        Mode: AG
[om]          Fan speed: a
[aqil]        Light brightness: 1
[uil]         Buttons light: ON
[ddp]         Used index: PM2.5
[cl]          Child lock: False
[fltsts0]     Pre-filter and Wick: clean in 23 hours
[fltsts1]     HEPA filter: replace in 3368 hours
[fltsts2]     Active carbon filter: replace in 0 hours

However, when I try to access it in homekit, I can see below error.
And actually I'd see the same if I test it with airctrol command without sudo, may I know how can I permit such access to fix it ?

7/5/2020, 11:54:49 AM Traceback (most recent call last):
7/5/2020, 11:54:49 AM File "/home/hoobs/.hoobs/node_modules/philips-air/pyaircontrol.py", line 123, in <module>
7/5/2020, 11:54:49 AM main()
7/5/2020, 11:54:49 AM File "/home/hoobs/.hoobs/node_modules/philips-air/pyaircontrol.py", line 104, in main
7/5/2020, 11:54:49 AM print(c.get_status())
7/5/2020, 11:54:49 AM File "/home/hoobs/.hoobs/node_modules/philips-air/pyaircontrol.py", line 68, in get_status
7/5/2020, 11:54:49 AM status = self._client.get_status(False)
7/5/2020, 11:54:49 AM File "/home/hoobs/.local/lib/python3.7/site-packages/pyairctrl/plain_coap_client.py", line 220, in get_status
7/5/2020, 11:54:49 AM status = self._get()
7/5/2020, 11:54:49 AM File "/home/hoobs/.local/lib/python3.7/site-packages/pyairctrl/plain_coap_client.py", line 50, in _get
7/5/2020, 11:54:49 AM self._send_hello_sequence(client)
7/5/2020, 11:54:49 AM File "/home/hoobs/.local/lib/python3.7/site-packages/pyairctrl/plain_coap_client.py", line 83, in _send_hello_sequence
7/5/2020, 11:54:49 AM self._send_over_socket(self.server, packet)
7/5/2020, 11:54:49 AM File "/home/hoobs/.local/lib/python3.7/site-packages/pyairctrl/plain_coap_client.py", line 38, in _send_over_socket
7/5/2020, 11:54:49 AM s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, protocol)
7/5/2020, 11:54:49 AM File "/usr/lib/python3.7/socket.py", line 151, in __init__
7/5/2020, 11:54:49 AM _socket.socket.__init__(self, family, type, proto, fileno)
7/5/2020, 11:54:49 AM PermissionError: [Errno 13] Permission denied

**Comment by Sunoo** [comment]
Interesting, airctrl really should work just fine without sudo. Do you remember exactly the command you used to install it? I wonder if it installed in some nonstandard way or something...

Also, can you let me know which OS you’re running this under?

**Comment by lhttony** [comment]
Hello, I'm running it with a HOOBS on a RPi4
the commands were just from the github readme.

Let me try it again with another spare pi

**Comment by Sunoo** [comment]
This jogged a memory a bit, and I remembered seeing people talking about needing sudo for CoAP on the py-air-control project page. You can see that discussion starting around this comment: https://github.com/rgerganov/py-air-control/issues/35#issuecomment-640271024

Can you see if what they discuss resolves needing root to run it for you? I think that problem is at the core of the plugin not working for you, as neither Homebridge or HOOBS runs as root (by default anyways, and it’d be a bad idea to change that).

**Comment by lhttony** [comment]
Hello, yea seems it's more appropriate to ask the py-air-control, and I get the solution here, FYI 
https://github.com/rgerganov/py-air-control/pull/49/commits/98e8fd8482386b2e8885ca767bdc774f759e4d98#diff-04c6e90faac2675aa89e2176d2eec7d8R96

it's simply solved by one more command :
sudo sysctl -w net.ipv4.ping_group_range="0 1000"

Thanks very much for your effort !

**Comment by Sunoo** [comment]
Awesome, I’ll update the readme tomorrow with that extra step. Looks like it must be specific to Plain CoAP units.

I might finally see if I can get a post install script together to automatically run these extra steps too.
