### ISSUE TITLE
Can't get config to work

### ISSUE THREAD

**Issue by MadAEng** [Sunoo/homebridge-philips-air#25]
Noob issue here....

I can't seem to get the config in working order. What I've got is this:

`{
    "bridge": {
        "name": "Homebridge XXXX",
        "username": "0E:XX:XX:XX:XX:D9",
        "port": 5xx0,
        "pin": "7XX-XX-XX0"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "platform": "philipsAir",
            "devices": [
                {
                    "name:": "Purifier",
                    "ip": "192.168.1.18",
                    "protocol": "http"
                }
            ]
        }
    ]
}`

With that, it won't run, the log file tells me:
`Error: Accessories must be created with a non-empty displayName.`
Followed by a string of other messages.

Where am I ffing up?

**Comment by Sunoo** [comment]
I don’t see anything obviously wrong with your config. The full error message would probably be helpful though.

Also, you seem to be using Config UI X, why not just use that to configure your plugins?

**Comment by MadAEng** [comment]
I’ve tried editing the settings for the plugin, but that doesn’t seem to make it work, also doesn’t change the config.
This is what I have in the config tab.
I’ll grab the full error message in the morning

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MadAEng** [comment]
I've restored the config back to default, and then set up the plugin in the UI.

Here's what the config looks like now, and below that the log, which it keeps cycling through:

`{
    "bridge": {
        "name": "Homebridge 68D9",
        "username": "0E:38:81:74:68:D9",
        "port": 51040,
        "pin": "770-31-130"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "devices": [
                {
                    "ip": "192.168.1.18",
                    "protocol": "http",
                    "sleep_speed": true
                }
            ],
            "name": "Philips Air",
            "timeout_seconds": 30,
            "platform": "philipsAir"
        }
    ]
}`


[HB Supervisor] Starting Homebridge with extra flags: -I
[HB Supervisor] Started Homebridge v1.1.1 with PID: 2668
Loaded config.json with 0 accessories and 2 platforms.
---
Loaded plugin: homebridge-config-ui-x@4.24.0
Registering platform 'homebridge-config-ui-x.config'
---
Loaded plugin: homebridge-philips-air@2.2.0
Registering platform 'homebridge-philips-air.philipsAir'
---
Loading 2 platforms...
[Config] Initializing config platform...
[Config] Running in Service Mode
[Philips Air] Initializing philipsAir platform...
[Philips Air] Initializing platform accessory undefined...
Error: Accessories must be created with a non-empty displayName.
    at new Accessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:230:29)
    at new PlatformAccessory (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:69:9)
    at PhilipsAirPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-philips-air/src/index.ts:397:19)
    at /usr/local/lib/node_modules/homebridge-philips-air/src/index.ts:56:43
    at Array.forEach (<anonymous>)
    at PhilipsAirPlatform.didFinishLaunching (/usr/local/lib/node_modules/homebridge-philips-air/src/index.ts:55:25)
    at HomebridgeAPI.emit (events.js:315:20)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:251:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:160:14)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
Got SIGTERM, shutting down Homebridge...
[HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[HB Supervisor] Restarting Homebridge...

**Comment by MadAEng** [comment]
I just tried to add a name in the config, one line above the IP:
`"name": "Living Room Purifier",`

Still won't work, logs now cycle through this:

[HB Supervisor] Starting Homebridge with extra flags: -I
[HB Supervisor] Started Homebridge v1.1.1 with PID: 1034
Loaded config.json with 0 accessories and 2 platforms.
---
Loaded plugin: homebridge-config-ui-x@4.24.0
Registering platform 'homebridge-config-ui-x.config'
---
Loaded plugin: homebridge-philips-air@2.2.0
Registering platform 'homebridge-philips-air.philipsAir'
---
Loading 2 platforms...
[Config] Initializing config platform...
[Config] Running in Service Mode
[Philips Air] Initializing philipsAir platform...
[Philips Air] Initializing platform accessory Living Room Purifier...
FetchError: request to http://192.168.1.18/di/v1/products/0/security failed, reason: connect ECONNREFUSED 192.168.1.18:80
    at Object.deserializeError (/usr/local/lib/node_modules/homebridge-philips-air/node_modules/sync-fetch/shared.js:93:12)
    at fetch (/usr/local/lib/node_modules/homebridge-philips-air/node_modules/sync-fetch/index.js:36:18)
    at HttpClient.getKey (/usr/local/lib/node_modules/homebridge-philips-air/node_modules/philips-air/src/HttpClient.ts:57:16)
    at new HttpClient (/usr/local/lib/node_modules/homebridge-philips-air/node_modules/philips-air/src/HttpClient.ts:44:23)
    at PhilipsAirPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-philips-air/src/index.ts:464:38)
    at /usr/local/lib/node_modules/homebridge-philips-air/src/index.ts:56:43
    at Array.forEach (<anonymous>)
    at PhilipsAirPlatform.didFinishLaunching (/usr/local/lib/node_modules/homebridge-philips-air/src/index.ts:55:25)
    at HomebridgeAPI.emit (events.js:315:20)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:251:10)
Got SIGTERM, shutting down Homebridge...
[HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[HB Supervisor] Restarting Homebridge...

**Comment by Sunoo** [comment]
The `ECONNREFUSED` message suggests that you are trying to use the wrong protocol for your purifier.

**Comment by MadAEng** [comment]
Changed it to coap, and that immediately did the trick, thnx!

How would I know in advance which one should work?
On a sidenote, would it be possible to get a readout of the sensors in HK?

**Comment by Sunoo** [comment]
Unfortunately I’m not aware of any way to tell which is the correct protocol to use at this point, it’s just trial and error.

What sensors were you hoping to have exposed? The air quality should show already.

**Comment by MadAEng** [comment]
Yeah, I spoke a bit to quick on that last bit, edited it out!

**Comment by Sunoo** [comment]
Sounds good, I’ll close this out then!
