### ISSUE TITLE
sensor read refresh time and filters status

### ISSUE THREAD

**Issue by belkone** [Sunoo/homebridge-philips-air#3]
Hi, at the beginning I would like to say that you did a great job!
But I have a question: when is air quality taken? can you force the sensor to refresh for example every 10 seconds?

It looks like the air quality is read once when starting homebridge and is not updated anymore.
In the code I also saw information about filters - unfortunately homebridge does not show this information anywhere?

My device: Philips AC2889 / 10

**Comment by jamesg311** [comment]
I have the same model. You were able to successfully pair it with HomeKit?

**Comment by Sunoo** [comment]
It should be updating based on the timeout_seconds parameter in your config, or defaulting to every 5 seconds if that value isn’t set. Is that not working correctly for you?

**Comment by belkone** [comment]
> I have the same model. You were able to successfully pair it with HomeKit?

yes, pairing is nice and quick, really @Sunoo did a really good job ;) 

> It should be updating based on the timeout_seconds parameter in your config, or defaulting to every 5 seconds if that value isn’t set. Is that not working correctly for you?

thanks for the reply, it was a premature alarm;)
I observed that the status refreshes when you re-enable the Home.app (just minimize).
It does not refresh while the application is still on the main screen - should it be?

**Comment by Sunoo** [comment]
The Home app is sometimes weird about when it actually shows new information. My plugin should be updating the data regularly, and asking Siri should always give the latest. I have however noticed, that sometimes the Home app just doesn't immediately update. There isn't much I can do about that. You could try Eve, that seems to be more consistent at showing the latest data.

**Comment by belkone** [comment]
Ok thanks, I think the issue could be closed because plugin is working correctly 🙂
