### ISSUE TITLE
Accessory not responding

### ISSUE THREAD

**Issue by MadAEng** [Sunoo/homebridge-philips-air#31]
Back again with another issue.

I tried to get it running on a Pi Zero running the homebridge image instead of using my 'desktop' raspi, now my purifier shows up in HK, but all I get from it is: "Not responding".
I've tried running the post-install steps, but still nothing.

Here's the log:

`Got SIGTERM, shutting down Homebridge...
[HB Supervisor] OS: Linux 5.4.51+ arm
[HB Supervisor] Node.js v12.18.2 /usr/local/bin/node
[HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
[HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[HB Supervisor] Delaying Homebridge startup by 20 seconds on low powered serverLoaded config.json with 0 accessories and 2 platforms.
---
Loaded plugin: homebridge-config-ui-x@4.25.1
Registering platform 'homebridge-config-ui-x.config'
---
Loaded plugin: homebridge-philips-air@2.2.0
Registering platform 'homebridge-philips-air.philipsAir'
---
Loading 2 platforms...
[Config] Initializing config platform...
[Config] Running in Service Mode
[Philips Air] Initializing philipsAir platform...
[Philips Air] Initializing platform accessory Purifier...
[Philips Air] Unable to load firmware info: Error: spawnSync python3 ETIMEDOUT
[Philips Air] Unable to load status info: Error: spawnSync python3 ETIMEDOUT
[Philips Air] Unable to load filter info: Error: spawnSync python3 ETIMEDOUT
Setup Payload:
X-HM://0024N25LG8K8K
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 7XX-XX-XX6 │     
    └────────────┘     
                       
Homebridge is running on port 5XX8.`

I tried to increase the time-out from 5 to 30 seconds, that takes away the load Errors, but other than that the result is still the same.

**Comment by Sunoo** [comment]
Sounds like python3 or some other dependency might not be installed correctly? How did you install the plugin?

**Comment by MadAEng** [comment]
I ran the command in the cli as described in the readme

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sunoo** [comment]
Did any errors occur during install? Are you sure you used `--unsafe-perm`?

If so, you could try going through the manual install steps: https://github.com/Sunoo/philips-air#manual-post-install-steps

**Comment by MadAEng** [comment]
I don't recall any errors, and I already ran the manual post install.

I tried running the install and post install again to see what comes up.

What stands out:
- When I run the 'normal' install again, it keeps telling me it has `updated 1 package`, every time.

- When running the post install, on step 3, (CoAPthon3 update) it tells me this:
`Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/Tanganelli/CoAPthon3@89d5173
  Cloning https://github.com/Tanganelli/CoAPthon3 (to revision 89d5173) to /tmp/pip-req-build-bi50626m
  Did not find branch or tag '89d5173', assuming revision or ref.
Building wheels for collected packages: CoAPthon3
  Running setup.py bdist_wheel for CoAPthon3 ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-ruehs1ry/wheels/63/8f/99/012c8b6374fe3a573d1106deeac84fa79e12b5be12fa19d457
Successfully built CoAPthon3
Installing collected packages: CoAPthon3
  Found existing installation: CoAPthon3 1.0.1
    Uninstalling CoAPthon3-1.0.1:
      Successfully uninstalled CoAPthon3-1.0.1
Successfully installed CoAPthon3-1.0.1`

**Comment by Sunoo** [comment]
That's expected. If you wanted to do a full reinstall, you have to `sudo npm uninstall -g homebridge-philips-air` first.

And CoAPthon always throws that during installation. I tried to find a way to tell it that is expected, but there didn't seem to be a way to do that.

**Comment by MadAEng** [comment]
I tried that, then reinstalled. Same result.
It did save the settings and config, but nothing noteworthy in the output as far as I can tell:

> 
> philips-air@0.4.0 postinstall /usr/local/lib/node_modules/homebridge-philips-air/node_modules/philips-air
> node postinstall.js

$ apt-get install -y python3-pip git
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version (1:2.20.1-2+deb10u3).
python3-pip is already the newest version (18.1-5+rpt1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

$ pip3 install -U py-air-control git+https://github.com/Tanganelli/CoAPthon3@89d5173
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/Tanganelli/CoAPthon3@89d5173
  Cloning https://github.com/Tanganelli/CoAPthon3 (to revision 89d5173) to /tmp/pip-req-build-1l20ivvv
  Did not find branch or tag '89d5173', assuming revision or ref.
Requirement already up-to-date: py-air-control in /usr/local/lib/python3.7/dist-packages (2.1.0)
Requirement already satisfied, skipping upgrade: pycryptodomex>=3.4.7 in /usr/local/lib/python3.7/dist-packages (from py-air-control) (3.9.8)
Building wheels for collected packages: CoAPthon3
  Running setup.py bdist_wheel for CoAPthon3 ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-lzo4yq08/wheels/63/8f/99/012c8b6374fe3a573d1106deeac84fa79e12b5be12fa19d457
Successfully built CoAPthon3
Installing collected packages: CoAPthon3
  Found existing installation: CoAPthon3 1.0.1
    Uninstalling CoAPthon3-1.0.1:
      Successfully uninstalled CoAPthon3-1.0.1
Successfully installed CoAPthon3-1.0.1

Checking /etc/sysctl.conf for net.ipv4.ping_group_range...
net.ipv4.ping_group_range already set:
         net.ipv4.ping_group_range=0 1000
net.ipv4.ping_group_range=0 1000

+ homebridge-philips-air@2.2.0
added 9 packages from 9 contributors in 78.66s

**Comment by Sunoo** [comment]
Huh, that all looks good, let me do some digging to see what I can figure out.

**Comment by MadAEng** [comment]
The logs now do show a spawn sync error, I've tried googling that, but none the wiser...

> [Config] Homebridge restart request received
> [Config] No restart command defined, killing process...
> [HB Supervisor] Stopping services...
> [HB Supervisor] OS: Linux 5.4.51+ arm
> [HB Supervisor] Node.js v12.18.2 /usr/local/bin/node
> [HB Supervisor] Homebridge Path: /usr/local/lib/node_modules/homebridge/bin/homebridge
> [HB Supervisor] UI Path: /usr/local/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
> [HB Supervisor] Delaying Homebridge startup by 20 seconds on low powered server
> [HB Supervisor] Starting Homebridge with extra flags: -I
> [HB Supervisor] Started Homebridge v1.1.2 with PID: 1859
> [Config] Homebridge Config UI X v4.25.2 is listening on :: port 8581
> Loaded config.json with 0 accessories and 2 platforms.
> ---
> Loaded plugin: homebridge-config-ui-x@4.25.2
> Registering platform 'homebridge-config-ui-x.config'
> ---
> Loaded plugin: homebridge-philips-air@2.2.0
> Registering platform 'homebridge-philips-air.philipsAir'
> ---
> Loading 2 platforms...
> [Config] Initializing config platform...
> [Config] Running in Service Mode
> [Philips Air] Initializing philipsAir platform...
> [Philips Air] Initializing platform accessory Purifier...
> [Philips Air] Unable to load firmware info: Error: spawnSync python3 ETIMEDOUT
> [Philips Air] Unable to load status info: Error: spawnSync python3 ETIMEDOUT
> [Philips Air] Unable to load filter info: Error: spawnSync python3 ETIMEDOUT
> Setup Payload:
> X-HM://0024N25LG8K8K
> Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
>                        
>     ┌────────────┐     
>     │ 7XX-XX-XX6 │     
>     └────────────┘     
>                        
> Homebridge is running on port 5XX8.

**Comment by Sunoo** [comment]
You never shared your config, so I can’t write up the exact command for you, but have you tried reading from your purifier using `airctrl`?

**Comment by MadAEng** [comment]
It's the same as in my previous issue ;), but I've inserted it below anyway.

No I haven't, how do I use airctrl?

> {
>     "bridge": {
>         "name": "Homebridge C086",
>         "username": "0X:XX:XX:XX:XX:X6",
>         "port": 5XX8,
>         "pin": "7XX-XX-XX6"
>     },
>     "accessories": [],
>     "platforms": [
>         {
>             "name": "Config",
>             "port": 8581,
>             "platform": "config"
>         },
>         {
>             "devices": [
>                 {
>                     "name": "Purifier",
>                     "ip": "192.168.1.18",
>                     "protocol": "coap",
>                     "sleep_speed": true
>                 }
>             ],
>             "name": "Philips Air",
>             "timeout_seconds": 30,
>             "platform": "philipsAir"
>         }
>     ]
> }

**Comment by Sunoo** [comment]
Oh right, sorry about that. I'm juggling a lot of open issues across several projects. Thanks for reposting it.

From the terminal, run `airctrl  --ipaddr 192.168.1.18 --protocol coap`, and let me know what happens.

**Comment by MadAEng** [comment]
Don't be sorry, I'm the one that feels like a pain in the rear coming up with issues ;)
Below the response, it then get stuck on that.

> Give up on message From None, To ('192.168.1.18', 5683), CON-6970, POST-vV, [Uri-Path: sys, Uri-Path: dev, Uri-Path: sync, ] B965EB45...8 bytes
> Traceback (most recent call last):
>   File "/usr/local/bin/airctrl", line 10, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.7/dist-packages/pyairctrl/airctrl.py", line 448, in main
>     c = CoAPCli(device["ip"], debug=args.debug)
>   File "/usr/local/lib/python3.7/dist-packages/pyairctrl/airctrl.py", line 15, in __init__
>     self._client = CoAPAirClient(host, port, debug)
>   File "/usr/local/lib/python3.7/dist-packages/pyairctrl/coap_client.py", line 80, in __init__
>     self._sync()
>   File "/usr/local/lib/python3.7/dist-packages/pyairctrl/coap_client.py", line 91, in _sync
>     self.client_key = self.client.post("/sys/dev/sync", self.syncrequest).payload
> AttributeError: 'NoneType' object has no attribute 'payload'

**Comment by Sunoo** [comment]
Okay, well at least now we have an error message. The best approach might be to open an issue with that project, but let me see what I can figure out first.

Are you sure the unit is using CoAP? You could try `airctrl --ipaddr 192.168.1.18 --protocol plain_coap` or `airctrl --ipaddr 192.168.1.18 --protocol http` and see if either of those work any better. I'm vaguely remember confirming that your unit doesn't use HTTP though.

**Comment by MadAEng** [comment]
I've tried all three already to no end.

Response using `plain_coap`:

> Give up on message From None, To ('192.168.1.18', 5683), CON-48366, EMPTY-None, [] No payload

Response using `http`:

> Exchanging secret key with the device ...
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/urllib/request.py", line 1324, in do_open
>     encode_chunked=req.has_header('Transfer-encoding'))
>   File "/usr/lib/python3.7/http/client.py", line 1244, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
>     self.send(msg)
>   File "/usr/lib/python3.7/http/client.py", line 966, in send
>     self.connect()
>   File "/usr/lib/python3.7/http/client.py", line 938, in connect
>     (self.host,self.port), self.timeout, self.source_address)
>   File "/usr/lib/python3.7/socket.py", line 727, in create_connection
>     raise err
>   File "/usr/lib/python3.7/socket.py", line 716, in create_connection
>     sock.connect(sa)
> ConnectionRefusedError: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/airctrl", line 10, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.7/dist-packages/pyairctrl/airctrl.py", line 444, in main
>     c = HTTPAirCli(device["ip"])
>   File "/usr/local/lib/python3.7/dist-packages/pyairctrl/airctrl.py", line 100, in __init__
>     self._client = HTTPAirClient(host, debug)
>   File "/usr/local/lib/python3.7/dist-packages/pyairctrl/http_client.py", line 108, in __init__
>     self.load_key()
>   File "/usr/local/lib/python3.7/dist-packages/pyairctrl/http_client.py", line 156, in load_key
>     self._get_key()
>   File "/usr/local/lib/python3.7/dist-packages/pyairctrl/http_client.py", line 119, in _get_key
>     with urllib.request.urlopen(req) as response:
>   File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "/usr/lib/python3.7/urllib/request.py", line 525, in open
>     response = self._open(req, data)
>   File "/usr/lib/python3.7/urllib/request.py", line 543, in _open
>     '_open', req)
>   File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python3.7/urllib/request.py", line 1352, in http_open
>     return self.do_open(http.client.HTTPConnection, req)
>   File "/usr/lib/python3.7/urllib/request.py", line 1326, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

**Comment by Sunoo** [comment]
I’d recommend taking the output of those 3 commands and opening an issue on py-air-control: https://github.com/rgerganov/py-air-control

**Comment by MadAEng** [comment]
Done.
I am running a AC1214/10 though, so I'm a bit confused as to which does what for which model.

**Comment by MadAEng** [comment]
Right, so I tried to run the airctrl soap command again a while later, now the response is this:

> [name]                        Name: Living Room
> [type]                        Type: AC1214
> [modelid]                     ModelId: AC1214/10
> [swversion]                   Version: 2.0.0
> [om]                          Fan speed: 2
> [pwr]                         Power: ON
> [cl]                          Child lock: False
> [aqil]                        Light brightness: 0
> [uil]                         Buttons light: OFF
> [mode]                        Mode: night
> [pm25]                        PM25: 31
> [iaql]                        Allergen index: 6
> [aqit]                        Air quality notification threshold: 10
> [ddp]                         Used index: IAI
> [fltt1]                       HEPA filter type: NanoProtect Filter Series 3 (FY2422)
> [fltt2]                       Active carbon filter type: NanoProtect Filter AC (FY2420)
> [fltsts0]                     Pre-filter and Wick: clean in 265 hours
> [fltsts1]                     HEPA filter: replace in 4705 hours
> [fltsts2]                     Active carbon filter: replace in 2305 hours
> [ota]                         Over the air updates: no
> [Runtime]                     Runtime: 0.91 hours
> [WifiVersion]                 WifiVersion: AWS_Philips_AIR@54.2
> [ProductId]                   ProductId: dca8c9d2f2ab11e8a1e3061302926720
> [DeviceId]                    DeviceId: 1c02e184da5a11eaa4baeadb19baab40
> [StatusType]                  StatusType: localcontrol
> [ConnectType]                 ConnectType: Localcontrol

Still the same result in HK though

**Comment by Sunoo** [comment]
Interesting, I wonder why that command only works sometimes for you...

**Comment by MadAEng** [comment]
Well, as Philips' own app isn't working consistently as well, that might be a result of the purifiers connection dropping out for some reason.

**Comment by Sunoo** [comment]
Sounds like that’s the root of the problem. Get the official app working first, and I think it should work in the plugin.

**Comment by MadAEng** [comment]
Right, so it seems that connection has held steady overnight, but the response is still #https://github.com/Sunoo/homebridge-philips-air/issues/31#issuecomment-674232092
