### ISSUE TITLE
"Unable to load key"

### ISSUE THREAD

**Issue by freakadings** [Sunoo/homebridge-philips-air#4]
Hey,
thank you for your plugin, i just installed it but it seems it can't connect to my airpurifier (AC 3036/10).

The IP is correct.

I tried to reset its WiFi-Connection but still the same message:

`"[philipsAir] Unable to load key: FetchError: request to http://192.168.178.72/di/v1/products/0/security failed, reason: connect ECONNREFUSED 192.168.178.72:80"`

Any help would be great :)

**Comment by Sunoo** [comment]
Sorry, I thought I replied to this, this seems to be related to issue #1 . More information can be found there if you want to follow that, but the short version is that Philips changed the way communication works with the newer models, and we haven’t quite figured it out yet (though people are getting very close).
