### ISSUE TITLE
Sleep mode

### ISSUE THREAD

**Issue by MattCheetham** [Sunoo/homebridge-philips-air#5]
At night I usually run my 2000i in sleep mode or sometimes in speed 1 with the light off.

I'd love to be able to achieve this with this plugin, and I see that you already interpret the fan speeds to set turbo. I'm wondering if there should be an option for one of the lower speeds before "off" to be sleep speed, just like turbo is maximum.

Similarly, it could be worth adding a standalone switch accessory to be able to turn the lights on or off on the unit. 

When I wake up I usually switch it back to allergen mode, but I can't think of a nice way to do this in HomeKit so, for now, I'll just do that manually in a morning.

I'm not much of a javascript developer but I am a software developer so I'm happy to have a go at putting something together and submitting as a pull request based on your existing code. Just wanted to get your opinion before I have a go at it as to what you think the best route for this kind of thing would be.

**Comment by Sunoo** [comment]
My unit does not seem to support sleep mode, so I wasn’t sure what to do with it when I was writing this plugin. It sounds like the best way to handle that would be a config option to enable it, then add it to the fan speed slider.

I’ve had another request just the other day about adding a separate “night mode” switch to control the lights, and I do plan to add that (probably with a config option to allow hiding it).

I never use allergen mode on my unit, so I don’t fully understand how it works with the other states of the machine, but I could add another switch device for that too?

I think these are good ideas, and am happy to implement them when I have a chance, though that might be a little bit. If you wanted to make a pull request, I’d be happy to accept it.

**Comment by MattCheetham** [comment]
Never did find time in my week off to look at this. Actually been getting on okay just switching it off at night (it’s been very warm and I have the windows open!). Will have a go if I find time in the future but for now it’s not likely.

**Comment by Sunoo** [comment]
I still plan to add it myself if I get a chance.

**Comment by Sunoo** [comment]
I've just pushed a new version that should add support for the 'sleep' speed. My unit doesn't support that, so I can't test it. If you can test when you have a chance, I'd appreciate it. It's done by turning the fan speed down the the bottom 20% while the sleep_speed config option is set.

I plan to work on the night mode switch tomorrow.

**Comment by MattCheetham** [comment]
It works! Thank you so much for this. I really appreciate the time you've put into this. If there's somewhere I can drop you a tip do let me know.

**Comment by Sunoo** [comment]
The “Sponsor” button at the top of the project page has links to ways to tip. So glad to hear the feature is working for you!
