### ISSUE TITLE
Light support

### ISSUE THREAD

**Issue by GorkaMM** [Sunoo/homebridge-philips-air#6]
Congratulations for such a great plugin! I've been using a complicated setup with a custom plugin and [py-air-control](https://github.com/rgerganov/py-air-control)'s CLI for quite long and it's nice to find an all-built-in approach here.

The only thing that this plugin is missing is purifiers' light support, which one of the forks has already implemented. It would be great if it could be added to yours :) https://github.com/pigri/homebridge-philips-air

**Comment by Sunoo** [comment]
I’m happy to add such a feature, in fact I was planning on working on it soon myself.

I’m a bit surprised that fork hasn’t submitted a pull request to get the feature added, but I’ll take a look at what they’ve done today.

**Comment by Sunoo** [comment]
I added support for the lights, can you please test when you have the chance? My unit doesn't seem to support the feature, so I was unable to test it myself.

**Comment by GorkaMM** [comment]
Thanks for such a quick change!

I tested it and the brightness is working properly but turning UI buttons on and off doesn't. My model is 3256/10 and has two lights:
* The colored circle. Uses `aqil` to set the brightness and accepts values from 0 to 100.
  * Currently working with your plugin.
* The button lights. Based on a 1 - 0 `uil` parameter that turns them ON and OFF with no fading.
  * Not working yet. The purifier doesn't seem to get any command here so it might just be a tiny thing with some `if`s…

![image](https://user-images.githubusercontent.com/1714234/83349330-69fc7100-a334-11ea-9394-9788e87488e2.png)

**Comment by GorkaMM** [comment]
I might have found the cause: setting the light is using the wrong parameter. It should set `uil` instead of mode: https://github.com/Sunoo/homebridge-philips-air/blob/1bef8cc92b7898ee4ba27cfc7f8f81aed68842c9/index.js#L284

Also, there might be some issues setting `uil` manually instead of reading it from the purifier as it's return among all other parameters. Maybe trying to read first before falling back to manually setting it would be great.

**Comment by Sunoo** [comment]
Ah, looks like I made a copy/paste error when I was setting up that section. I can fix that part easy enough.

Also, it seems like these are two completely discrete lights, perhaps it makes more sense to expose two different light bulbs for them? Seems a bit odd for one control to control two things. The only reason I linked them is because I misunderstood the way it works. Let me know your thoughts on that.

**Comment by GorkaMM** [comment]
They're different lights but I think they serve the same purpose so I personally prefer to have them under a single control linked to the purifier. That way I can turn them on and off directly and set the brightness for the one that allows it. My use case is that I turn all lights off when going to sleep and have all lights on at a 100% brightness during the day.

What do you think?

**Comment by Sunoo** [comment]
Makes sense to me. I’ll try to get the bugs fixed this afternoon and get a new version pushed for you to test. Since it’s more than just buttons, I’ll probably change the name of the config option too.

**Comment by Sunoo** [comment]
Okay, I've made some tweaks and pushed a new version, let me know how this works for you.

**Comment by GorkaMM** [comment]
Thanks for the update! I tested it and now lights are not working at all. I’ll try to take some time to do some changes myself and test it so we can find out the correct way to manage lights. 

It’s weird it doesn’t even set the brightness now, so maybe a little bug showed up when implementing the changes.

**Comment by Sunoo** [comment]
Interesting, I wonder how I mangled that... it’s tricky for me to implement since I don’t have access to a unit that supports the lights. If you’re able to get them working, I’m more than happy to accept a pull request and get the functionality added.

**Comment by lightingcze** [comment]
Hi, I have AC2889/10 and light control doesnt work :-(

**Comment by lightingcze** [comment]
Something was happened last night. From today ( in CZE) morning is working both. The switch dim out display and fader dimming colored status led.
Thank you guys;-)

**Comment by Sunoo** [comment]
Interesting... @GorkaMM can you retest when you have a chance? Maybe try clearing out the cache from Homebridge?

**Comment by dsadsa897897r** [comment]
Hello - this is working for me, but the layout in the home app in the detail panel with the light bulb option is very strange on an iPhone X - can send screenshot if useful

**Comment by Sunoo** [comment]
Please send a screenshot, that should help me understand better.

**Comment by dsadsa897897r** [comment]
![IMG_1522](https://user-images.githubusercontent.com/7852568/84074903-3d4af800-a9cb-11ea-9866-595085455c52.PNG)

**Comment by Sunoo** [comment]
Ah, yea, that is a bit messy... I could possibly expose it as a separate device, but that would complicate things a bunch.

Is using “Show as Separate Tiles” (you should see it if you scroll down a bit) a reasonable solution for you? That’s what I use personally, so I guess I didn’t really notice how ugly that is during development.

**Comment by dsadsa897897r** [comment]
no big issue, but thought you might be interested - wasn't sure if there as a way to tell apple how to do the layout.

Separating the tiles works for me, but interestingly the light switch toggle seems to be unreliable -  the fading works but the toggle appears to only adjust the illumination of the numbers on the top rather than the blue ring

**Comment by Sunoo** [comment]
I think I can fix toggle to control both sets of lights. I’ll just update the light toggle to also set the brightness to 0 when turning off the light, and that should work how you expect. It was hard for me to know for sure how it worked, since my unit doesn’t support these light controls.

**Comment by dsadsa897897r** [comment]
I think that would make sense.

Your work on this plugin is much appreciated - Thank You!

**Comment by lightingcze** [comment]
O like as it is, want to have switch off just display not central polution led circle. Pls keep it separated ;-)

Ondřej Bylok
LD / Avolites & gMA2 operator-programmer / 
+420604830049
Prague CZE

**Comment by Sunoo** [comment]
How about two separate lightbulb devices? One dimmable, and one on/off, that way you have full control over the two different lights?

**Comment by lightingcze** [comment]
Yes that’s the acceptable way for me ;-)

Ondřej Bylok
LD / Avolites & gMA2 operator-programmer / 
+420604830049
Prague CZE

**Comment by Sunoo** [comment]
Okay, I've updated light support to expose the two different lights as separate lightbulbs, which makes the most sense to me based on my understanding of the units with lights. If anyone with one of those units can test, please let me know if everything is working.

As a bonus, having an extra device now seems to make it show up a lot cleaner in the single tile view in the Home app.

**Comment by lightingcze** [comment]
I have this problem.



Ondřej Bylok
LD / Avolites & gMA2 operator-programmer / 
+420604830049
Prague CZE

**Comment by lightingcze** [comment]
So after clear cache it’s bit better.


Ondřej Bylok
LD / Avolites & gMA2 operator-programmer / 
+420604830049
Prague CZE

**Comment by Sunoo** [comment]
I’m sorry, which problem did you have?

I’m not sure why a cache clear was needed, but if that resolved the problem, that’s fine I guess?

**Comment by lightingcze** [comment]
And in HomeApp it’s all okay.
So good job 👏🏻 

Ondřej Bylok
LD / Avolites & gMA2 operator-programmer / 
+420604830049
Prague CZE

**Comment by lightingcze** [comment]
It was problems with starting home bridge.

Ondřej Bylok
LD / Avolites & gMA2 operator-programmer / 
+420604830049
Prague CZE

**Comment by Sunoo** [comment]
Ah, okay. Sorry I didn’t catch that, but hopefully anyone hitting that thinks to clear their cache, since that typically resolves those issues. If I have some time this afternoon, I may see if I can catch the issue and resolve it.

In the meantime, given that light support seems to be working, I’m going to close this issue out.
