### ISSUE TITLE
AC1000i ECONNRESE Issue

### ISSUE THREAD

**Issue by ethempekin** [Sunoo/homebridge-philips-air#7]
Hello,

I am getting this problem. Is it because of the update?

Unable to load key: FetchError: request to http://192.168.1.48/di/v1/products/0/security failed, reason: read ECONNRESE

**Comment by Sunoo** [comment]
Was it working before you updated? That looks like you probably have one of the newer models not supported by this yet.

**Comment by ethempekin** [comment]
> Was it working before you updated? That looks like you probably have one of the newer models not supported by this yet.

It had some problems. Mine is series 1000i so an old version. In my json config i might mess up things.

**Comment by Sunoo** [comment]
Interesting, I don’t recall changing anything in recent versions other than light support, and even that shouldn’t impact anything at all if you don’t enable it. I personally own a 1000i (AC1214/40), so the older models at least should be well supported. Does it work from the official Air Matters app?

**Comment by ethempekin** [comment]
It was fine on the clean home+ app.I have rebooted my Hoobs. Also replug the air prufier. Now o. Homekit is responding and i see no error in hoobs log. Let’s see how it goes.

**Comment by Sunoo** [comment]
Odd, but glad the error seems to be resolved for you, at least for now. I’ll keep this open for a few days, in case it comes back. If it happens after that, of course feel free to reopen the issue and we’ll try to get to the bottom of it. Right now my best guess is something to do with your network though.

**Comment by ethempekin** [comment]
Thank you very much. I will keep you posted. Indeed my home network might cause this as well.

**Comment by ethempekin** [comment]
Hi again.
This time the following happened:

`11/06/2020, 23:42:24 [Philips Air] Initializing platform accessory Air Prufier...
11/06/2020, 23:42:27 [Philips Air] Unable to load firmware info: SyntaxError: Unexpected end of JSON input
11/06/2020, 23:42:27 [Philips Air] Unable to load status info: SyntaxError: Unexpected end of JSON input
11/06/2020, 23:42:27 [Philips Air] Unable to load filter info: SyntaxError: Unexpected end of JSON input `

**Comment by Sunoo** [comment]
Is that actually preventing it from working? I've see similar errors on rare occasions, but they've never actually seemed to impede functionality. My guess is that the purifier just returns garbage occasionally for some reason.

**Comment by ethempekin** [comment]
Probably it was not the real problem. I see in the log that it did not continue but the prufier was not responding and it didn’t auto shut off this night.

I had problems with Nest protect as well. Maybe that causes homebridge to fail each time. 

`12/06/2020, 02:23:29 [Nest] API observe: error Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_INTERNAL_ERROR
    at ClientHttp2Stream._destroy (internal/http2/core.js:2101:13)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:38:8)
    at ClientHttp2Stream.[kMaybeDestroy] (internal/http2/core.js:2117:12)
    at Http2Stream.onStreamClose (internal/http2/core.js:493:26) {
  code: 'ERR_HTTP2_STREAM_ERROR'
}
12/06/2020, 02:23:29 [Nest] Retrying in 10 seconds.
12/06/2020, 03:53:40 [Nest] API observe: error Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:200:27) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read'
}
12/06/2020, 03:53:40 [Nest] Retrying in 10 seconds. `

**Comment by Sunoo** [comment]
Seems likely that this is something going on either with your network, or possibly whatever device you’re running Homebridge on. Unfortunately, I’m not sure I can be much more help here.

**Comment by ethempekin** [comment]
Thanks. I will try to solve  it another way.

**Comment by Sunoo** [comment]
Might be worth asking in the Homebridge Discord: https://discord.gg/Z8jmyvb

Good luck.
