### ISSUE TITLE
After update, HB cant startup

### ISSUE THREAD

**Issue by lightingcze** [Sunoo/homebridge-philips-air#8]
Hi today after update plugin the HB dont startup anymore. :-(

**Comment by Sunoo** [comment]
Please follow the first 3 steps of the installation instructions:

1. Install pip using sudo apt install python3-pip.
2. Install rpi-rf using sudo pip3 install py-air-control.
3. Update CoAPthon3 using sudo pip3 install -U git+https://github.com/Tanganelli/CoAPthon3@89d5173.

**Comment by lightingcze** [comment]
So its necessary to install something more?
It’s strange if you just update plugin :-(

Ondřej Bylok
LD / Avolites & gMA2 operator-programmer / 
+420604830049
Prague CZE

**Comment by Sunoo** [comment]
Yes, it was necessary for me to support the newer models.

**Comment by lumaxis** [comment]
I think I might have the same issue. I think I have all the python package dependencies installed correctly, at least `airctrl --ipaddr $MY_IP --protocol coap` works as expected. 
However, homebridge is cycling now:

```
0|homebridge  | [6/15/2020, 4:49:30 PM] [philipsAir] Initializing philipsAir platform...
PM2           | App [homebridge:0] exited with code [0] via signal [SIGSEGV]
PM2           | App [homebridge:0] starting in -fork mode-
PM2           | App [homebridge:0] online
```

I haven't been able to get a more useful stacktrace of the error unfortunately. Is there anywhere specific I should look to debug this?

**Comment by Sunoo** [comment]
Interesting, not sure what’s causing that. Could you provide a full log, preferably from debug mode, and your config.json?

**Comment by Sunoo** [comment]
Also, just a thought, for people who don’t need the newer models, I could publish the older version of the plugin as homebridge-philips-air-httponly or something, which would avoid needing any of the new Python stuff.

**Comment by Sunoo** [comment]
@lightingcze I went ahead and published homebridge-philips-air-httponly, which currently is just the previous version, so doesn't require any of the python stuff. I will try to keep it current with any updates I make to the main branch though. Feel free to switch to this version if you prefer not to install any extra components.

**Comment by lightingcze** [comment]
![4487DE79-01E0-4312-B816-A12FA998FB7F](https://user-images.githubusercontent.com/18398709/84677885-a08adc00-af2f-11ea-9149-2dcda3d2dd65.png)
I w sending also print screen but now i didn’t see here. So this was showing me and running in cycles.

**Comment by Sunoo** [comment]
@lightingcze Looks like you haven’t installed the Python components. You’ll need to do that or switch to the httponly version.

**Comment by lightingcze** [comment]
okay, i’m whole day at work so i’ll install requested components. But as i can say as user, it would be great if necessary components will install together or after some check before update processing ;-)

**Comment by Sunoo** [comment]
@lightingcze I’ll look into that to see if it’s an option. That would certainly be a much preferable solution.

**Comment by lumaxis** [comment]
@Sunoo I played around in the Node REPL a bit and it's the `python.importSync('pyairctrl.http_client')` call that's triggering the seg fault. (Same for all the other import calls btw.)

My understanding of the Python ecosystem is fairly limited, so not really an idea what's going on 🤔 I'm assuming it might have to do with me being on FreeBSD?

For completeness sake, this is my `config.json`:
```json
  "platforms": [
    {
      "platform": "philipsAir",
      "devices": [
        {
          "name": "Luftreiniger",
          "ip": "192.168.0.189",
          "protocol": "coap",
          "sleep_speed": true
        }
      ]
    }
  ]
```

**Comment by Sunoo** [comment]
@lumaxis Interesting, I assume you installed the Python components with pip as the instructions specify? Although that’s not the error I’d expect to see if you hadn’t.

I’ll play around after work today and see if I can figure out how to recreate it...

**Comment by lumaxis** [comment]
Yea, everything installed as instructed. And as I mentioned, calling the `pyairctrl` library directly on the command line works fine

**Comment by Sunoo** [comment]
Thanks for that information, hopefully I can get to the bottom of this soon.

**Comment by Sunoo** [comment]
@lumaxis I tried everything I could think of, and wasn’t able to recreate the problem on Linux. I’m assuming it is something related to you running on FreeBSD, but I’m not too familiar with that OS. If I have some free time soon, I’ll try spinning up a FreeBSD virtual machine, but I’m not sure I know enough to find a solution.

**Comment by chrispi68** [comment]
I also had problems with the new version and could not get it working. Actually it broke my Homebridge installation after starting the upgrade with "homebridge-config-ui-x".

I installed homebridge-philips-air-httponly, did the setup with the "homebridge-config-ui-x" but this did not work either. With the old version, everything was working without any problems.

I would suggest to revert "homebridge-philips-air" to the working version and publish a new version "homebridge-philips-air-2" with the new features so we can do a proper beta test.

**Comment by Sunoo** [comment]
@chrispi68 Could you provide more information about what broke? It’s interesting that you say the httponly version doesn’t work for you either, because that is literally just the previous version. For what it’s worth, I use Config UI X on my setup, and was able to upgrade to 2.0.0 in it without issue, provided I installed the Python components.

It would help to see both the logs from your Homebridge and your config.json so I can try to understand what your problem is.

**Comment by chrispi68** [comment]
I found the cause for the problem. I had to uninstall "homebridge-philips-air". After this "homebridge-philips-air-httponly" was working again. I think there is a conflict when "homebridge-philips-air-httponly" and "homebridge-philips-air" are both installed because the "platform" attribute is "philipsAir" for both plugins.

**Comment by Sunoo** [comment]
@chrispi68 Ah yes, I didn’t want to change the attribute so people wouldn’t have to change their config. I couldn’t think of any reason to have both versions installed together. Glad you got it working.
