### ISSUE TITLE
Speed in Home app not displayed correctly / Changing speed in Home app not working

### ISSUE THREAD

**Issue by phm46** [Sunoo/homebridge-philips-air#85]
Hey!
I love your plugin, however I have issues with it. I have AC3059/50 and I'm using coap protocol. I'm able to turn on/off purifier, however speed in Home app is always set to 0 (see screenshot bellow) and when I change it, nothing happens (changing mode to sleep/turbo).

Am I doing something wrong? I'm running homebridge on Raspberry Pi 2 model B - I don't know if this problem can be related to performance.

![image](https://user-images.githubusercontent.com/3530536/98355302-3e3b9080-2022-11eb-983a-0daebccd9d87.png)
![image](https://user-images.githubusercontent.com/3530536/98355281-367bec00-2022-11eb-97b4-638e3705e6e4.png)

**Comment by swl2861** [comment]
I have the same missing fan speed control issue with my 2889/10, also no air quality readout. The lights dim function is working properly tho :)

**Comment by Sunoo** [comment]
Can one of you tell me the output of airctrl? Sounds like your units must be doing speed controls different than mine.

**Comment by swl2861** [comment]
C:\Windows\System32>airctrl --ipaddr 192.168.2.8
Exchanging secret key with the device ...
Traceback (most recent call last):
  File "c:\python39\lib\urllib\request.py", line 1342, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "c:\python39\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\python39\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\python39\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\python39\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "c:\python39\lib\http\client.py", line 950, in send
    self.connect()
  File "c:\python39\lib\http\client.py", line 921, in connect
    self.sock = self._create_connection(
  File "c:\python39\lib\socket.py", line 843, in create_connection
    raise err
  File "c:\python39\lib\socket.py", line 831, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\airctrl.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\pyairctrl\airctrl.py", line 444, in main
    c = HTTPAirCli(device["ip"])
  File "c:\python39\lib\site-packages\pyairctrl\airctrl.py", line 100, in __init__
    self._client = HTTPAirClient(host, debug)
  File "c:\python39\lib\site-packages\pyairctrl\http_client.py", line 108, in __init__
    self.load_key()
  File "c:\python39\lib\site-packages\pyairctrl\http_client.py", line 156, in load_key
    self._get_key()
  File "c:\python39\lib\site-packages\pyairctrl\http_client.py", line 119, in _get_key
    with urllib.request.urlopen(req) as response:
  File "c:\python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "c:\python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "c:\python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "c:\python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "c:\python39\lib\urllib\request.py", line 1371, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "c:\python39\lib\urllib\request.py", line 1345, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>

**Comment by Sunoo** [comment]
You'll need to specific --protocol coap (I think, I don't have the commands in front of me at the moment).

**Comment by swl2861** [comment]
C:\Windows\System32>airctrl --ipaddr 192.168.2.8 --protocol coap
Unexpected error:'Thread' object has no attribute 'isAlive'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "c:\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "c:\python39\lib\site-packages\coapthon\client\coap.py", line 273, in receive_datagram
    self._send_ack(transaction)
  File "c:\python39\lib\site-packages\coapthon\client\coap.py", line 307, in _send_ack
    self.send_datagram(ack)
  File "c:\python39\lib\site-packages\coapthon\client\coap.py", line 170, in send_datagram
    if self._receiver_thread is None or not self._receiver_thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'

**Comment by Sunoo** [comment]
That's unexpected. Might be worth opening an issue with the py-air-control project to see if they can get that working for you.

**Comment by swl2861** [comment]
I'm trying something else first :)

**Comment by swl2861** [comment]
Nope, didn't work... I'm making a new issue... thnx for your time

**Comment by phm46** [comment]
> Can one of you tell me the output of airctrl? Sounds like your units must be doing speed controls different than mine.

Sure, there is output:
```[name]                        Name: Living Room
[type]                        Type: AC3059
[modelid]                     ModelId: AC3059/50
[swversion]                   Version: Ms3102
[language]                    language: EN
[DeviceVersion]               DeviceVersion: 1.0.2
[om]                          Fan speed: 1
[pwr]                         Power: ON
[cl]                          Child lock: False
[aqil]                        Light brightness: 100
[uil]                         Buttons light: ON
[uaset]                       uaset: A
[mode]                        Mode: AG
[pm25]                        PM25: 4
[iaql]                        Allergen index: 1
[aqit]                        Air quality notification threshold: 7
[tvoc]                        Total volatile organic compounds: 1
[ddp]                         Used index: PM2.5
[rddp]                        rddp: 1
[fltt1]                       HEPA filter type: NanoProtect Filter Series 3 (FY2422)
[fltt2]                       Active carbon filter type: none
[fltsts0]                     Pre-filter and Wick: clean in 275 hours
[fltsts1]                     HEPA filter: replace in 4800 hours
[fltsts2]                     Active carbon filter: replace in 65535 hours
[filna]                       filna: 0
[filid]                       filid: 0
[ota]                         Over the air updates: ck
[Runtime]                     Runtime: 13.61 hours
[WifiVersion]                 WifiVersion: AWS_Philips_AIR@54.2
[ProductId]                   ProductId: bd5f6b3a13c111e9bc6802024953075e
[DeviceId]                    DeviceId: ea9a198a1dea11ebb4bdc6e5469eb434
[StatusType]                  StatusType: localcontrol
[ConnectType]                 ConnectType: Localcontrol
```

**Comment by Sunoo** [comment]
Thanks. It’s super late here, so I may be missing something, but it looks like speed should match what I’m sending. Something else must be different somewhere...

**Comment by phm46** [comment]
> Thanks. It’s super late here, so I may be missing something, but it looks like speed should match what I’m sending. Something else must be different somewhere...

No problem :)

Just to give you more data, I tried all three modes (auto, sleep and turbo) and here is output of `om` parameter:
Turbo mode - `turbo`
Auto - `1`
Sleep mode - `silent`

Also I'm able to change speed (mode) with following commands:
Turbo: `airctrl --ipaddr [IP] --protocol coap --om t --mode T`
Sleep: `airctrl --ipaddr [IP] --protocol coap --om s --mode S`
Auto: `airctrl --ipaddr [IP] --protocol coap --om a --mode A`

**Comment by Sunoo** [comment]
Does setting it in airctrl work? I’m assuming not.

**Comment by phm46** [comment]
Yes, using commands above I'm able to change speed/mode to auto/turbo/sleep.

**Comment by Sunoo** [comment]
Interesting. Definitely need to take a closer look at all this when I’m actually awake. Something must be different.

**Comment by phm46** [comment]
Sure. I'll try to look at source code and see what's going on. It will be hard because I've never used typescript :) I'll let you know in case of any updates.

**Comment by Sunoo** [comment]
If you happen to be familiar with JavaScript, you should be able to read TypeScript well enough.

**Comment by phm46** [comment]
Ok so here is what I've found:
I don't know history of the code or why it's there but on line 200, there is IF statement. My purifier never had mode "M" (maybe it's for older models?), so it won't update speed. My purifier have modes A, T, S for Auto, Turbo, Sleep. For testing purposes I changed this line to `if(true)` and now it properly updates speed in Home app.

For speed change, it is also related to mode. You are manually setting mode to `M`, however as I wrote, my purifier uses different modes. So I changed it like this:
```
            if (speed > 0) {
                const values = {
                    mode: '',
                    om: ''
                };
                if (offset == 1 && speed == 1) {
                    values.om = 's';
                    values.mode = 'S';
                }
                else if (speed < 4 + offset) {
                    values.om = (speed - offset).toString();
                    values.mode = 'A';
                }
                else {
                    values.om = 't';
                    values.mode = 'T';
                }
```

Now both things work - getting and setting speed. However I saw one more thing happening there. I don't know why, but sometimes when I change speed, setFan function is triggered and after few seconds it's triggered second time. It can be easily solved with IF statement - change speed only if new speed is different than old speed.

**Comment by Sunoo** [comment]
On my unit, “M” mode needs to be set to put it in manual (as opposed to auto), but it is an older, HTTP-based unit.

**Comment by phm46** [comment]
Ok, that’s why I made it backward compatible. In case someone has newer device, he just need to tick checkbox in config.

**Comment by Sunoo** [comment]
Perfect, I hadn't actually looked at your code change yet. I'll probably dig in to that this afternoon.

**Comment by phm46** [comment]
Any updates?

**Comment by phm46** [comment]
Bump

**Comment by rimonhanna** [comment]
I have a similar issue, any update?
