### ISSUE TITLE
I can't get the Philips air to work

### ISSUE THREAD

**Issue by swl2861** [Sunoo/homebridge-philips-air#86]
Hi,

First I need to address my limited knowledge of scripting and that I'm using a Windows 10 client. I have followed the steps in the installation instructions but I don't get it to work. Because I'm using Windows 10 and the CoAP protocol I already found out that npt didn't work for me so I've used Chocolatey. The rest seems installed normally. When I restart my Homebridge I'm getting this output:

6-11-2020 16:38:43] [Philips Air] [Philips 2889/10] Unable to load firmware info: Error: spawnSync python3 ENOENT
[6-11-2020 16:38:43] [Philips Air] [Philips 2889/10] Unable to load status info: Error: spawnSync python3 ENOENT
[6-11-2020 16:38:43] [Philips Air] [Philips 2889/10] Unable to load filter info: Error: spawnSync python3 ENOENT

Hope you can help me!

**Comment by Sunoo** [comment]
I haven't done much testing on Windows, but that looks like it can't find Python on your system.

**Comment by swl2861** [comment]
Ah ok, Should I install Python from a windows executable (I have already) or from within npm?

**Comment by Sunoo** [comment]
Python isn't in npm, I would have assumed installing it would work. Something must be odd with the way the Windows installer works. It needs to be in your path, and I would have thought it would go there by default.

**Comment by swl2861** [comment]
ok, thanks for the clarification, I'm going check some things and maybe reinstall python3

**Comment by swl2861** [comment]
Would it be a problem if I have both Pythonv2 and v3?

**Comment by Sunoo** [comment]
I did all my testing on Python 3, I'm not sure if Python 2 would work.

**Comment by swl2861** [comment]
hmmm no luck :( - I'll sleep on it, untill I have new idea's

**Comment by swl2861** [comment]
I have found a forumtopic about a issue for the missing python3 command, Python3 on Windows has 2 ways to call: py and python. The workaround is to make a copy of python.exe and name it to python3.exe. This works but the next error is this: [6-11-2020 23:33:25] [Philips Air] [Philips 2889/10] Unable to load filter info: Error: Command failed: python3 C:\Users\TV\AppData\Roaming\npm\node_modules\homebridge-philips-air\node_modules\philips-air/pyaircontrol.py --ipaddr 192.168.2.8 --protocol coap --status
Traceback (most recent call last):
  File "C:\Users\TV\AppData\Roaming\npm\node_modules\homebridge-philips-air\node_modules\philips-air\pyaircontrol.py", line 8, in <module>
    from pyairctrl.coap_client import CoAPAirClient
ModuleNotFoundError: No module named 'pyairctrl'

**Comment by swl2861** [comment]
Solved! uninstalling and reinstalling (pip3 install py-air-control)  :)

**Comment by Sunoo** [comment]
Fantastic! Glad you were able to work it out.
